
services:
  app:
    image: banking-microservice1:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" 
       #8000
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: banking_db
    ports:
      - "3306:3306"
